### ISSUE TITLE
Does this do anything as of now?

### ISSUE THREAD

**Issue by Tranberry** [MAOstrander/ArkhamAdventure#12]
**If so** what do I need to make it do anything, as it was html I just grabbed it and tried to open the index.html file - the collapsed areas did not open when clicked on in fact _clicking on anything at all did nothing._ 

I tried different browsers; chrome, firefox, internet explorer and edge - windows 10. Now I'll probably try to understand what a .json file is and if I need to put this on a server or compile something. 

Anyway keep at it / Oskar TRBRY

**Comment by MAOstrander** [comment]
You are correct, as of now this doesn't do much. This is/was one of my earliest forays into html/javascript and I initially bit off more than I can chew. While I was still in the middle of changing the site design and layout I ended up learning  some different technologies that made me want to try and develop this as a phone app first, then a website second.

Currently the best bet to see what I have so far is to visit this link here:
https://github.com/MAOstrander/Arkham-Adventure-App/blob/master/www/index.html

I apologize, I will make a concerted effort to update the documentation within a week or two.
